version: '3.8'
services:
  mongo:
    build:
      context: ./mongo
      dockerfile: mongo/Dockerfile
    ports:
      - "27017:27017"

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
